# fly.toml app configuration file generated for financereact on 2024-10-03T19:10:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# https://financereact.fly.dev/
# npm run build
# flyctl launch


app = 'financereact'
primary_region = 'sea'

[build]

[[statics]]
  guest_path = "/app/client/build"
  url_prefix = "/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
